import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

import './globals.css';

const notoSans = Noto_Sans({ variable: '--font-sans' });

export const metadata: Metadata = {
  title: '（New Concept English',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
